--liquibase formatted sql

--changeset ledger:001-create-accounts
create table accounts (
    id            bigint generated by default as identity primary key,
    name          varchar(255) not null unique,
    type          varchar(255) not null,
    currency      varchar(255) not null,
    balance_minor bigint       not null,
    version       bigint       not null
);
--rollback drop table accounts;

--changeset ledger:002-create-journal-entries
create table journal_entries (
    id              bigint generated by default as identity primary key,
    idempotency_key varchar(255) not null unique,
    description     varchar(255) not null,
    created_at      timestamp with time zone not null
);
--rollback drop table journal_entries;

--changeset ledger:003-create-postings
create table postings (
    id           bigint generated by default as identity primary key,
    entry_id     bigint not null references journal_entries (id),
    account_id   bigint not null references accounts (id),
    amount_minor bigint not null
);
create index idx_postings_account_recent on postings (account_id, id desc);
create index idx_postings_entry on postings (entry_id);
--rollback drop table postings;
